### YamlMime:UniversalReference
items:
  - uid: office.OneNote_Application
    summary: >-
      Represents the top-level object that contains all globally addressable OneNote objects such as notebooks, the
      active notebook, and the active section. 

       \[Api set: OneNoteApi 1.1\]
    name: OneNote_Application
    fullName: office.OneNote_Application
    langs:
      - typeScript
    type: class
    extends:
      - OfficeExtension.ClientObject
    package: office
    children:
      - office.OneNote_Application.getActiveNotebook
      - office.OneNote_Application.getActiveNotebookOrNull
      - office.OneNote_Application.getActiveOutline
      - office.OneNote_Application.getActiveOutlineOrNull
      - office.OneNote_Application.getActivePage
      - office.OneNote_Application.getActivePageOrNull
      - office.OneNote_Application.getActiveSection
      - office.OneNote_Application.getActiveSectionOrNull
      - office.OneNote_Application.load
      - office.OneNote_Application.navigateToPage
      - office.OneNote_Application.navigateToPageWithClientUrl
      - office.OneNote_Application.notebooks
  - uid: office.OneNote_Application.getActiveNotebook
    summary: |-
      Gets the active notebook if one exists. If no notebook is active, throws ItemNotFound. 

       \[Api set: OneNoteApi 1.1\]
    name: getActiveNotebook()
    fullName: office.OneNote_Application.getActiveNotebook
    langs:
      - typeScript
    type: method
    syntax:
      content: 'getActiveNotebook(): OneNote.Notebook;'
      return:
        type:
          - OneNote.Notebook
        description: ''
  - uid: office.OneNote_Application.getActiveNotebookOrNull
    summary: |-
      Gets the active notebook if one exists. If no notebook is active, returns null. 

       \[Api set: OneNoteApi 1.1\]
    name: getActiveNotebookOrNull()
    fullName: office.OneNote_Application.getActiveNotebookOrNull
    langs:
      - typeScript
    type: method
    syntax:
      content: 'getActiveNotebookOrNull(): OneNote.Notebook;'
      return:
        type:
          - OneNote.Notebook
        description: ''
  - uid: office.OneNote_Application.getActiveOutline
    summary: |-
      Gets the active outline if one exists, If no outline is active, throws ItemNotFound. 

       \[Api set: OneNoteApi 1.1\]
    name: getActiveOutline()
    fullName: office.OneNote_Application.getActiveOutline
    langs:
      - typeScript
    type: method
    syntax:
      content: 'getActiveOutline(): OneNote.Outline;'
      return:
        type:
          - OneNote.Outline
        description: ''
  - uid: office.OneNote_Application.getActiveOutlineOrNull
    summary: |-
      Gets the active outline if one exists, otherwise returns null. 

       \[Api set: OneNoteApi 1.1\]
    name: getActiveOutlineOrNull()
    fullName: office.OneNote_Application.getActiveOutlineOrNull
    langs:
      - typeScript
    type: method
    syntax:
      content: 'getActiveOutlineOrNull(): OneNote.Outline;'
      return:
        type:
          - OneNote.Outline
        description: ''
  - uid: office.OneNote_Application.getActivePage
    summary: |-
      Gets the active page if one exists. If no page is active, throws ItemNotFound. 

       \[Api set: OneNoteApi 1.1\]
    name: getActivePage()
    fullName: office.OneNote_Application.getActivePage
    langs:
      - typeScript
    type: method
    syntax:
      content: 'getActivePage(): OneNote.Page;'
      return:
        type:
          - OneNote.Page
        description: ''
  - uid: office.OneNote_Application.getActivePageOrNull
    summary: |-
      Gets the active page if one exists. If no page is active, returns null. 

       \[Api set: OneNoteApi 1.1\]
    name: getActivePageOrNull()
    fullName: office.OneNote_Application.getActivePageOrNull
    langs:
      - typeScript
    type: method
    syntax:
      content: 'getActivePageOrNull(): OneNote.Page;'
      return:
        type:
          - OneNote.Page
        description: ''
  - uid: office.OneNote_Application.getActiveSection
    summary: |-
      Gets the active section if one exists. If no section is active, throws ItemNotFound. 

       \[Api set: OneNoteApi 1.1\]
    name: getActiveSection()
    fullName: office.OneNote_Application.getActiveSection
    langs:
      - typeScript
    type: method
    syntax:
      content: 'getActiveSection(): OneNote.Section;'
      return:
        type:
          - OneNote.Section
        description: ''
  - uid: office.OneNote_Application.getActiveSectionOrNull
    summary: |-
      Gets the active section if one exists. If no section is active, returns null. 

       \[Api set: OneNoteApi 1.1\]
    name: getActiveSectionOrNull()
    fullName: office.OneNote_Application.getActiveSectionOrNull
    langs:
      - typeScript
    type: method
    syntax:
      content: 'getActiveSectionOrNull(): OneNote.Section;'
      return:
        type:
          - OneNote.Section
        description: ''
  - uid: office.OneNote_Application.load
    summary: >-
      Queues up a command to load the specified properties of the object. You must call "context.sync()" before reading
      the properties.
    name: load(option)
    fullName: office.OneNote_Application.load
    langs:
      - typeScript
    type: method
    syntax:
      content: 'load(option?: string | string[] | OfficeExtension.LoadOption): OneNote.Application;'
      return:
        type:
          - OneNote.Application
        description: ''
      parameters:
        - id: option
          description: ''
          type:
            - 'string | string[] | OfficeExtension.LoadOption'
  - uid: office.OneNote_Application.navigateToPage
    summary: Opens the specified page in the application instance.
    name: navigateToPage(page)
    fullName: office.OneNote_Application.navigateToPage
    langs:
      - typeScript
    type: method
    syntax:
      content: 'navigateToPage(page: OneNote.Page): void;'
      return:
        type:
          - void
        description: ''
      parameters:
        - id: page
          description: ''
          type:
            - OneNote.Page
  - uid: office.OneNote_Application.navigateToPageWithClientUrl
    summary: 'Gets the specified page, and opens it in the application instance.'
    name: navigateToPageWithClientUrl(url)
    fullName: office.OneNote_Application.navigateToPageWithClientUrl
    langs:
      - typeScript
    type: method
    syntax:
      content: 'navigateToPageWithClientUrl(url: string): OneNote.Page;'
      return:
        type:
          - OneNote.Page
        description: ''
      parameters:
        - id: url
          description: ''
          type:
            - string
  - uid: office.OneNote_Application.notebooks
    summary: >-
      Gets the collection of notebooks that are open in the OneNote application instance. In OneNote Online, only one
      notebook at a time is open in the application instance. Read-only. 

       \[Api set: OneNoteApi 1.1\]
    name: notebooks
    fullName: office.OneNote_Application.notebooks
    langs:
      - typeScript
    type: property
    syntax:
      content: 'notebooks: OneNote.NotebookCollection;'
      return:
        type:
          - OneNote.NotebookCollection
